# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7501644dad9b3c758dfeea2d4605ef2d8d7930407ab77987fd7653d362e17e68f52771ec6ae74ef26887cb817ecbe6abeeafcfe8f52bfb9cecb49df48e6471ce

test:
  secret_key_base: 37bc94c74154112b514aac233f306af9a9b7e781116cb7d219be7079d6769528d56d919871fee87e9236a9ac586d90526ffca3da367238fa569a981ff176f142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
